<?php

namespace App\Views;

use App\App;

class Navigation extends \Core\View
{
    public function __construct()
    {
        parent::__construct($this->generate());
    }

    public function generate()
    {
        $nav = ['/index.php' => 'All Wishes'];

        if (App::$session->getUser()) {
            if (App::$session->getUser()['email'] === 'santa@santa.lt'){

                return $nav + [
                        '/logout.php' => 'Logout',
                    ];

            } else {

                return $nav + [
                        '/Admin/add.php' => 'Make a Wish',
                        '/Admin/list.php' => 'My Wishes',
                        '/logout.php' => 'Logout',
                    ];
            }
        } else {
            return $nav + [
                    '/register.php' => 'Register',
                    '/login.php' => 'Login',
                    '/about.php' => 'About',
                ];
        }
    }

    function render($template_path = ROOT . '/app/templates/nav.tpl.php')
    {
        return parent::render($template_path); // TODO: Change the autogenerated stub
    }
}